services:
  web:
    container_name: ai4d-topic-toolkit
    # image: set to ${REGISTRY}/${PROJECT}:${TAG} for your deploy target
    image: ai4d-topic-toolkit:latest
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    command: gunicorn -w 4 -b 0.0.0.0:8000 ai4d_topic_toolkit.wsgi:application --timeout 300
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - hf_cache:/root/.cache/huggingface
      - .env:/usr/src/app/.env
    environment:
      DJANGO_SETTINGS_MODULE: ai4d_topic_toolkit.settings.staging
    depends_on:
      - db

  db:
    container_name: ai4d-topic-toolkit-db
    image: postgres:17.6
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data/
    command: postgres -c max_connections=1000

volumes:
  static_volume:
  db_volume:
  hf_cache:
