# Generated by Django 5.2.8 on 2026-03-31 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('raw_topics', models.JSONField(default=list)),
                ('normalized', models.JSONField(default=list)),
                ('backend', models.CharField(choices=[('llm', 'LLM'), ('embedding', 'Embedding')], max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label_en', models.CharField(max_length=200)),
                ('labels', models.JSONField(default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='topic_extraction.topic')),
            ],
        ),
    ]
