# Generated by Django 5.2.8 on 2026-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
