# Generated by Django 5.2.8 on 2026-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_extraction', '0002_topic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletopic',
            name='taxonomy_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
