# Generated by Django 5.2.8 on 2026-05-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_extraction', '0003_articletopic_taxonomy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletopic',
            name='language_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
