# Generated by Django 5.2.8 on 2026-05-22 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_extraction', '0004_articletopic_language_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('vector', models.JSONField()),
                ('embedding_model_name', models.CharField(max_length=200)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'language', 'embedding_model_name'], name='topic_extra_platfor_2cfb4e_idx')],
                'unique_together': {('platform', 'article_id')},
            },
        ),
    ]
