# Generated by Django 5.2.8 on 2026-05-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_extraction', '0005_articleembedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleembedding',
            options={'ordering': ['-computed_at']},
        ),
    ]
